---
- name: Обновление ПО из локального репозитория
  hosts: clients
  become: yes

  tasks:
    - name: Обновить кэш
      ansible.builtin.apt:
        update_cache: yes

    - name: Обновить установленные пакеты
      ansible.builtin.apt:
        upgrade: dist
